### PR TITLE
Composable envs on modern Nickel

### PR DESCRIPTION
**Pull request by thufschmitt**
This is a merge of #33 and #34 (since they were quite heavily conflicting). Could either merge this directly or cherry-pick this into one of them to make it possible to merge them sequentially

### CODE REVIEW

**Comment by yannham** [comment]
It's strange, `NixString` contract doesn't seem to be updated in this version.

**Comment by yannham** [comment]
(This part e.g.: https://github.com/nickel-lang/nickel-nix/pull/37/commits/78fe382e0cac3eacbc481e4d4ec9e8268f72d00f#diff-c0c73e6da72ae44caaf6f8fc765eb14c59fc836937c792188e59825282fd9b86R143)

**Comment by thufschmitt** [comment]
Mh, I might have messed something up in the merge :thinking:

**Comment by yannham** [comment]
Dan's PR has been merged, and we still have to cleanly adapt the code for the new symbolic string structure. Will do that from a clean state.

**Pull request closed without merging**
